development:
  cloud_name: ddmovditn
  api_key: 143535593614143
  api_secret: Q9de7cQcJbpoT07tQlz0xPuJsFc
  enhance_image_tag: true
  static_image_support: false
production:
  cloud_name: ddmovditn
  api_key: 143535593614143
  api_secret: Q9de7cQcJbpoT07tQlz0xPuJsFc
  enhance_image_tag: true
  static_image_support: true
test:
  cloud_name: ddmovditn
  api_key: 143535593614143
  api_secret: Q9de7cQcJbpoT07tQlz0xPuJsFc
  enhance_image_tag: true
  static_image_support: false